spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.chat.model=nvidia/nemotron-3-super-120b-a12b
spring.ai.openai.chat.temperature=0.2
spring.ai.openai.chat.max-tokens=2048
spring.ai.openai.chat.connection-pool-metrics-enabled=false